# Generated by Django 4.0.6 on 2022-08-01 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_featured_products_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('placed_at',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, null=True, to='store.promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
